language: cpp
compiler: gcc
dist: jammy

services:
  - docker

matrix:
  include:
    - name: "ROS2 project"
      before_install:
        - sudo apt-get update
        - sudo apt-get upgrade
        - sudo apt-get update && sudo apt-get install curl
        - sudo curl -sSL https://raw.githubusercontent.com/ros/rosdistro/master/ros.key -o /usr/share/keyrings/ros-archive-keyring.gpg
        - sudo sh -c 'echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/ros-archive-keyring.gpg] http://packages.ros.org/ros2/ubuntu $(. /etc/os-release && echo $UBUNTU_CODENAME) main" | sudo tee /etc/apt/sources.list.d/ros2.list > /dev/null'
        - sudo apt-get update
      install:
        - sudo apt-get install ros-humble-desktop
        - sudo apt-get install -y build-essential cmake git
        - sudo apt-get install python3-colcon-common-extensions
        - cd ros2
        #- colcon build
      script:
        #- cd ros2
        #- colcon test
      after_success:
        - bash <(curl -s https://codecov.io/bash) -X gcov -f "!*/ros2_ws/*"

    - name: "Machine Learning project"
      language: python
      python:
        - "3.8"
      before_install:
        - cd machine-learning
      install:
        - pip3 install -r requirements.txt
        #- python3 setup.py install
      script:
        #- pytest --cov=./
      after_success:
        - bash <(curl -s https://codecov.io/bash)
